site_logo: /images/logo.png
avatarUri: /images/avatar.jpg

customStyles:
  images: # 图片相关设置
    banner: /images/banner_dark.png # 站点横幅
    # background: /images/bg.png # 站点背景

snow: true

topMenu:
  - label: 首页
    icon: home
    url: /
  - label: 归档
    icon: file
    url: /archives/
  - label: 链接
    icon: paw
    url: /friends/
  - label: 其他
    icon: link
    submenu:
      - label: 简书
        url: https://www.jianshu.com/u/006751bcf229
      - label: b站
        url: https://space.bilibili.com/290552481
      - label: 推特
        url: https://twitter.com/6cq6t78JwKOlHui
      - label: IG
        url: https://www.instagram.com/yuxiaoyu822/

# group_link: https://matrix.to/#/#CandyUnion:nya.one
footerLinks:
  - icon: github
    link: https://github.com/yuxiaoyujun
  # - icon: rss
  #   link: /atom.xml

vendors:
  # 常用CDN基地址:
  # https://unpkg.com/
  # https://cdn.jsdelivr.net/npm/

  # 以下一行代码指定 npm cdn 基地址，该 CDN 应该兼容 jsdelivr 使用的路径格式
  # npm_cdn: https://cdn.jsdelivr.net/npm/
  packages:
    hexo-theme-kratos-rebirth: 
      # 以下一行代码用于对某个包单独配置 cdn 基地址，使用 null 表示不从 cdn 获取此包
      # cdn_url: null
      # cdn_url: https://cdn.jsdelivr.net/npm/hexo-theme-kratos-rebirth@latest/
    aplayer:
      enabled: true
      # 以下一行代码指定所使用的库版本
      # 默认情况下会使用主题开发组进行开发调试时所使用的版本（通常而言也是最适合的版本）
      # 因此该值不建议修改
      # 
      # 注意：如果选择其他版本，则必须配置 npm_cdn 或 为包单独配置 cdn_url 或 修改 vendors 目录，
      # 这是因为主题自带的库只含有默认版本，必须从 cdn 加载其他版本或由用户手动提供其他版本的相关文件
      #
      # 警告：随意切换版本可能造成主题无法正常工作
      # 
      order: random
      version: 1.10.1
      autoplay: true
      playlist: '/music/prayerX.mp3'
      fixed: true
      files:
        "dist/APlayer.min.css":
          # 以下代码用于单独对某个文件进行映射，以便于使用不符合 jsdelivr 路径格式的CDN（或其他特殊情形）
          # 使用 null 表示不重定向（默认行为）
          # relocate: null
          relocate: https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css

          # 以下代码用于指定 SRI 以增强安全性
          # 注意，仅有部分组件支持 SRI，不支持的组件会忽略此值
          # integrity: sha256-6Y7CJDaltoeNgk+ZftgCD9jLgmGv4xKUo8nQ0HgAwVo=

friends:
  list:
  - name: "Midjourney结果图"
    bio: "可以看看别人生成的图，然后可以复制关键词吖什么的"
    avatar: "../images/midjourney.jpeg"
    link: "https://www.midjourney.com/showcase/recent/"
  - name: "chatGpt"
    bio: "ChatGPT是由OpenAI开发的一个人工智能聊天机器人程序，于2022年11月推出。该程序使用基于GPT-3.5架构的大型语言模型并通过强化学习进行训练。"
    avatar: "../images/chatGpt.png"
    link: "https://chat.openai.com/chat"
  - name: "Mj各种参考"
    bio: "willwulfken整理：Mj各种参考，包含各种命令、参数、风格、打光等的实图对比"
    avatar: "../images/midjourney.jpeg"
    link: "https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference"
  - name: "akinator"
    bio: "神灯精灵，类似bing读心机器人的小游戏"
    avatar: "../images/akinator.jpeg"
    link: "https://cn.akinator.com/game"
  - name: "colab"
    bio: "google免费代码部署系统"
    avatar: "../images/colab.png"
    link: "https://colab.research.google.com/"
  - name: "PDF之家"
    bio: "免费下载PDF的网站"
    avatar: "../images/PDF.jpeg"
    link: "https://homeofpdf.com/index.html"
  - name: "sms-activate"
    bio: "租国外电话号"
    avatar: "../images/sms-activate.jpeg"
    link: "https://sms-activate.org/getNumberl"
  - name: "TXT to SRT"
    bio: "剪辑视频时自动生成字幕，pr的字幕太难用了"
    avatar: "../images/avatar.webp"
    link: "https://converts.me/tools/conversion/subtitle/txt-to-srt"
  - name: "petalica"
    bio: "线稿自动上色，是这样的，本身线稿画的好出图结果就会好。"
    avatar: "../images/petalica.png"
    link: "https://petalica.com/index_zh.html"
  - name: "站长字体"
    bio: "免费字体下载"
    avatar: "../images/chinaz.jpeg"
    link: "https://font.chinaz.com/"
  - name: "line-of-action"
    bio: "速写练习"
    avatar: "../images/lineofaction.png"
    link: "https://line-of-action.com/"
  - name: "爱给"
    bio: "免费bgm下载，剪辑用"
    avatar: "../images/aigei.png"
    link: "https://www.aigei.com/music/class/quiet_7/"
  - name: "舞力全开2020"
    bio: "卡带丢掉后的代替用品。。"
    avatar: "../images/wuliquankai.png"
    link: "https://www.bilibili.com/video/BV13E411t7Tw/?p=38"
  - name: "fandom"
    bio: "这还用介绍？"
    avatar: "../images/fandom.png"
    link: "https://www.fandom.com/"

posts:
  show_cc: true
  donate: true
  share: true
  comments: 
    provider: gitalk

gitalk:
  clientID: '628850ddd59360af6fad'
  clientSecret: 'f8dd6f68eace9e06f1a51496ff85dc8a4f48cef1'
  repo: 'yuxiaoyujun.github.io'
  owner: 'yuxiaoyujun'
  admin: 
    - 'yuxiaoyujun'
  # id: {{ location.pathname }}  # 默认id为页面完整链接，由于名称超过50字，gitalk无法在issus中生成评论，所以id指定为pathname，能短一点点
  distractionFreeMode: false

jsconfig:
  main:
    cover: 1
    expire_day: 1
    siteLeaveEvent: false
